name: FastAsyncWorldEdit
main: com.boydti.fawe.bukkit.v1_7.BukkitMain_17
version: ${version}
description: Fast Async WorldEdit plugin
authors: [Empire92]
loadbefore: [WorldEdit,AsyncWorldEdit,AsyncWorldEditInjector]
load: STARTUP
database: false
#softdepend: [WorldGuard, PlotSquared, MCore, Factions, GriefPrevention, Residence, Towny, PlotMe, PreciousStones]
commands:
  wea:
    description: (FAWE) Bypass WorldEdit processing and area restrictions
    aliases: [weanywhere,worldeditanywhere,/wea,/weanywhere,/worldeditanywhere]
    usage: "Vault is required for the toggle. Optionally, you can set the permission fawe.bypass"
  fawe:
    description: (FAWE) Reload the plugin
    aliases: [/fawe,/fawereload]
  select:
    description: (FAWE) Select your current WorldEdit Region.
    aliases: [/select,wer,/wer,worldeditregion,/worldeditregion,/region]
  fcancel:
    description: (FAWE) Cancel your edit
    aliases: [fawecancel,/fcancel,/cancel,/fawecancel]
  '/p':
    description: VoxelSniper perform command
    aliases: [perform,/perform]
  '/d':
    description: VoxelSniper default command
    aliases: [default,/default]
permissions:
  fawe.bypass:
    default: false
  fawe.admin:
    default: false
  fawe.stream:
    default: false
  fawe.reload:
    default: false
